"""PDF report generation for CareRisk AI."""

from datetime import datetime
from io import BytesIO
from typing import Dict, List, Any

from fpdf import FPDF


class CareRiskPDF(FPDF):
    def header(self):
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "CareRisk AI - Risk Assessment Report", ln=True, align="C")
        self.ln(4)

    def footer(self):
        self.set_y(-18)
        self.set_font("Arial", "I", 8)
        self.multi_cell(
            0,
            5,
            "This report is generated by an educational ML project and is not medical advice.",
            align="C",
        )


def _safe_text(value: Any) -> str:
    """FPDF with Arial works best with Latin-1 text."""
    text = str(value)
    return text.encode("latin-1", errors="ignore").decode("latin-1")


def generate_report(
    patient_data: Dict[str, Any],
    disease_type: str,
    prediction: int,
    probability: float,
    risk_level: str,
    top_factors: List[Dict[str, Any]],
) -> bytes:
    """Generate a downloadable PDF report and return bytes."""
    pdf = CareRiskPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.cell(0, 8, f"Disease module: {_safe_text(disease_type)}", ln=True)
    pdf.cell(0, 8, f"Prediction class: {prediction}", ln=True)
    pdf.cell(0, 8, f"Risk probability: {probability * 100:.2f}%", ln=True)
    pdf.cell(0, 8, f"Risk level: {_safe_text(risk_level)}", ln=True)
    pdf.ln(4)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Patient Input Data", ln=True)
    pdf.set_font("Arial", "", 10)
    for key, value in patient_data.items():
        pdf.cell(0, 7, f"{_safe_text(key)}: {_safe_text(value)}", ln=True)

    pdf.ln(4)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Important Risk Factors", ln=True)
    pdf.set_font("Arial", "", 10)
    if top_factors:
        for item in top_factors:
            feature = _safe_text(item.get("feature", "Unknown"))
            importance = float(item.get("importance", 0))
            pdf.cell(0, 7, f"- {feature}: {importance:.3f}", ln=True)
    else:
        pdf.cell(0, 7, "No feature importance available.", ln=True)

    pdf.ln(5)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 8, "Medical Disclaimer", ln=True)
    pdf.set_font("Arial", "", 10)
    pdf.multi_cell(
        0,
        6,
        "CareRisk AI is not a medical device. It does not provide diagnosis, treatment, "
        "or medical advice. The prediction is generated by a machine learning model and "
        "may be inaccurate. Always consult a qualified healthcare professional.",
    )

    output = pdf.output(dest="S")
    if isinstance(output, str):
        return output.encode("latin-1", errors="ignore")
    if isinstance(output, bytearray):
        return bytes(output)
    return output
